### ISSUE TITLE
Create app icon

### ISSUE THREAD

**Issue by skmanish** [Sweekrity-7392/BreMo#9]

**Comment by Sweekrity-7392** [comment]
![app_icon](https://user-images.githubusercontent.com/55786474/141760550-d83434c3-16a6-4dfc-8185-948cb5d80f77.png)

Icon_iteration 1

**Comment by skmanish** [comment]
Make another iteration of the character without any text anywhere

**Comment by Sweekrity-7392** [comment]
![icon](https://user-images.githubusercontent.com/55786474/142137383-3a946be7-c1bb-4ada-a08d-834b764cfdbd.png)



Icon_iteration 2

**Comment by Sweekrity-7392** [comment]
how about the second iteration?

**Comment by skmanish** [comment]
Looks good to me. Small details like skirt lines and shadow reflection on head etc will get lost in low resolution rendering of an icon.

Make this as your app icon and send a PR.

**Comment by Sweekrity-7392** [comment]
okay
